### ISSUE TITLE
Possible to use with PhantomJS or Electron?

### ISSUE THREAD

**Issue by LeMoussel** [esha/domx#1]
Hi,
Do you think that it's possible to use DomX with [PhantomJS](https://github.com/ariya/phantomjs) or [Electron](https://github.com/atom/electron)?

**Comment by nbubna** [comment]
The DOMx tests are run in PhantomJS by the build script. I haven't used Electron, but basically, if it has the standard DOM globals (e.g. ```document```, ```NodeList```, ```DocumentFragment```, ...), then it should work. If it doesn't have those, then it won't work.

Put succinctly, DOMx should work if the platform implements the DOM. :)

**Comment by LeMoussel** [comment]
I did not find the DOMx tests that are run in PhantomJS by the build script. 
Can you specify some examples?

**Comment by nbubna** [comment]
Well, all of the [DOMx test code](https://github.com/esha/domx/tree/master/test) is run by [grunt-contrib-qunit](https://github.com/gruntjs/grunt-contrib-qunit) which runs the tests in a headless phantomjs instance.

To see it in action (not that there's much to see), checkout the project, run ```npm install && grunt test```.
