### ISSUE TITLE
Emmet does not create img src url correctly

### ISSUE THREAD

**Issue by Demotis** [esha/domx#3]
When using the insert with emmet shorthand, it does not create the src correctly. I am doing this ...

`document.query("#TopNav").insert("div>img[src=text.png]")`

I expect to get this as the contents ....

`<div><img src="text.png"></div>`

but instead I get this ....

`<div><img src="tex" class="png]"></div>`

**Comment by nbubna** [comment]
Argh. Yeah, brackets should trump dots. I should have some time later today to look into this.

**Comment by nbubna** [comment]
Oops, responded before coffee. Yes, this is unintuitive, but you should be using ```[src="text.png"]```. Quoting attributes that aren't straight up alphanumeric is always recommended. Though, i think i may still try and make this work. :)

**Comment by nbubna** [comment]
Ok, it should work now, with or without quotes. Also, you can now escape end brackets in attributes (e.g. ```div[arr=foo[\]])``` -> ```<div arr="foo[]"></div>```) and end braces in text (e.g. ```span{{\} are braces}``` -> ```<span>{} are braces</span>```).

**Comment by nbubna** [comment]
In v0.17.1, that is.
